# overrides for local development, not used in CI
version: '3'
services:
  playwright:
    build:
      context: playwright
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-playwright:5-41cdfea42908830b8722c550e4070ef9
        platforms:
          - linux/amd64
          - linux/arm64
        cache-from:
          - type=registry,ref=registry.lil.tools/harvardlil/perma-playwright:buildcache
        cache-to:
          - type=registry,ref=registry.lil.tools/harvardlil/perma-playwright:buildcache,mode=max
      x-hash-paths:
        - requirements.txt
  web:
    build:
      context: .
      dockerfile: perma_web/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-web:17-6eb5a72e288f9870ccd10dc35d40253d
        platforms:
          - linux/amd64
          - linux/arm64
        cache-from:
          - type=registry,ref=registry.lil.tools/harvardlil/perma-web:buildcache
        cache-to:
          - type=registry,ref=registry.lil.tools/harvardlil/perma-web:buildcache,mode=max
      x-hash-paths:
        - perma_web/requirements.txt
        - perma_web/npm-shrinkwrap.json
        - perma_web/package.json
        - perma_web/perma-warcprox-ca.pem
        - perma_web/lil-archive-keyring.gpg
