# overrides for local development, not used in CI
version: '3'
services:
  playwright:
    build:
      context: playwright
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-playwright:2-afa23747554bc5f6419b9937cf34dd30
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - requirements.txt
  web:
    build:
      context: .
      dockerfile: perma_web/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-web:8-090caa14326d348c5a76d867be4de242
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - perma_web/requirements.txt
        - perma_web/npm-shrinkwrap.json
        - perma_web/package.json
        - perma_web/perma-warcprox-ca.pem
        - perma_web/lil-archive-keyring.gpg
