# overrides for local development, not used in CI
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: perma_web/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-web:21-0b1ade7b3dd3d9b35221336683af7d8c
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - perma_web/requirements.txt
        - perma_web/npm-shrinkwrap.json
        - perma_web/package.json
        - perma_web/perma-warcprox-ca.pem
        - perma_web/lil-archive-keyring.gpg
