# overrides for local development, not used in CI
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: perma_web/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-web:18-e35142d756ef6bbfc20db15d952ae10c
        platforms:
          - linux/amd64
          - linux/arm64
        cache-from:
          - type=registry,ref=registry.lil.tools/harvardlil/perma-web:buildcache
        cache-to:
          - type=registry,ref=registry.lil.tools/harvardlil/perma-web:buildcache,mode=max
      x-hash-paths:
        - perma_web/requirements.txt
        - perma_web/npm-shrinkwrap.json
        - perma_web/package.json
        - perma_web/perma-warcprox-ca.pem
        - perma_web/lil-archive-keyring.gpg
